frame_2_regular_1_data = {
    "addresses": {
        "billing": {
            "additional": "Jihoceský kraj",
            "city": "Bechyne",
            "collectionPoint": None,
            "countryCode": "DE",
            "firstName": "Pledra",
            "gender": "m",
            "houseNumber": "1966",
            "lastName": "Team",
            "phoneNumber": "00420266772600",
            "street": "Školní",
            "streetHouseNumber": "Školní 1966",
            "zipCode": "391 65",
        },
        "shipping": {
            "additional": "Jihoceský kraj",
            "city": "Bechyne",
            "collectionPoint": None,
            "countryCode": "DE",
            "firstName": "Pledra",
            "gender": "m",
            "houseNumber": "1966",
            "lastName": "Team",
            "phoneNumber": "00420266772600",
            "state": None,
            "street": "Školní",
            "streetHouseNumber": "Školní 1966",
            "zipCode": "391 65",
        },
    },
    "branchNumber": "0189",
    "carrier": {"key": "EXPRESS"},
    "companyId": 1000,
    "cost": {
        "appliedFees": [
            {
                "amount": {"withTax": 5900, "withoutTax": 4876},
                "category": "delivery",
                "key": "postcz_standard",
                "option": "deliveryCosts",
                "tax": {"vat": {"amount": 1024, "rate": 0.21}},
            }
        ],
        "costCapture": 21200,
        "tax": {"vat": {"amount": 4252}},
        "withTax": 21200,
        "withTaxWithMembershipDiscountWithoutServiceCosts": 21200,
        "withoutTax": 16948,
        "withoutTaxWithMembershipDiscount": 16948,
    },
    "countryCode": "de",
    "customData": {"branchNumber": "0189"},
    "customer": {
        "customData": [],
        "email": "team@pledra.com",
        "publicKey": "763",
        "referenceKey": "763",
        "taxNumber": None,
        "vendorReferenceKey": None,
    },
    "customerPublicKey": None,
    "fulfillingMerchantKey": "fim",
    "id": 5656,
    "items": [
        {
            "currencyCode": "EUR",
            "customData": {
                "aybaOttoReservationDetails": [],
                "prescriptionValues": {
                    "left": {"axis": 2, "cylinder": -2.5, "pd": 25.5, "sphere": -4.5},
                    "right": {"axis": 1, "cylinder": -3.25, "pd": 25, "sphere": -5.5},
                },
                "prescriptionValuesDisplay": {
                    "left": {
                        "axis": "2",
                        "cylinder": "-2,50",
                        "pd": "25,5",
                        "sphere": "-4,50",
                    },
                    "right": {
                        "axis": "1",
                        "cylinder": "-3,25",
                        "pd": "25,0",
                        "sphere": "-5,50",
                    },
                },
                "shopId": 10005,
            },
            "id": 17009,
            "itemGroup": {"id": "28486286", "isMainItem": True, "isRequired": True},
            "localizedName": "Fielmann MC 592 CL",
            "merchantKey": "default",
            "merchantProductVariantId": 154691,
            "merchantProductVariantReferenceKey": "24434",
            "merchantReservationKey": None,
            "name": "Fielmann MC 592 CL",
            "orderItemId": 66254693892149,
            "packagingGroupId": None,
            "price": 10000,
            "priceWithoutTax": 8000,
            "productVariantId": 154691,
            "quantity": 1,
            "shippingWarehouseReferenceKey": "FRAME",
            "subItems": [
                {
                    "attributes": [
                        {
                            "isLocked": False,
                            "name": "rxLensType",
                            "type": "simple",
                            "value": "ei",
                        },
                        {
                            "isLocked": False,
                            "name": "rxVariantSorting",
                            "type": "simple",
                            "value": "1",
                        },
                        {
                            "isLocked": False,
                            "name": "isSellableForFree",
                            "type": "simple",
                            "value": "True",
                        },
                        {
                            "isLocked": False,
                            "name": "rxAdditionalInfo",
                            "type": "localizedString",
                            "value": {"de_DE": "Einstärke"},
                        },
                    ],
                    "currencyCode": "EUR",
                    "customData": {
                        "aybaOttoReservationDetails": [],
                        "hideSubItem": True,
                        "shopId": 10005,
                    },
                    "id": 17005,
                    "itemGroup": {
                        "id": "28486286",
                        "isMainItem": False,
                        "isRequired": True,
                    },
                    "localizedName": "Nové: Jednoohniskové brýle",
                    "merchantKey": "default",
                    "merchantProductVariantId": 142934,
                    "merchantProductVariantReferenceKey": "type_ei",
                    "merchantReservationKey": None,
                    "name": "Neu: Brille mit Einstärkengläsern",
                    "orderItemId": 66254693892159,
                    "packagingGroupId": None,
                    "price": 100,
                    "priceWithoutTax": 79,
                    "productVariantId": 142934,
                    "quantity": 1,
                    "shippingWarehouseReferenceKey": "FRAME",
                    "tax": 21,
                    "taxAmount": 21,
                    "vendorReferenceKey": None,
                    "vendorSize": None,
                    "warehouseReferenceKey": "FRAME",
                },
                {
                    "attributes": [
                        {
                            "isLocked": False,
                            "name": "isSellableForFree",
                            "type": "simple",
                            "value": "True",
                        },
                        {
                            "isLocked": False,
                            "name": "rxVariantSorting",
                            "type": "simple",
                            "value": "6",
                        },
                        {
                            "isLocked": True,
                            "name": "rxLensIndex",
                            "type": "simple",
                            "value": "cd",
                        },
                        {
                            "isLocked": False,
                            "name": "rxAdditionalInfo",
                            "type": "localizedString",
                            "value": {
                                "de_DE": "Kunststoff Asphärisch 1,67 Brechungsindex"
                            },
                        },
                    ],
                    "currencyCode": "EUR",
                    "customData": {
                        "aybaOttoReservationDetails": [],
                        "hideSubItem": True,
                        "shopId": 10005,
                    },
                    "id": 17006,
                    "itemGroup": {
                        "id": "28486286",
                        "isMainItem": False,
                        "isRequired": True,
                    },
                    "localizedName": "Comfort Select",
                    "merchantKey": "default",
                    "merchantProductVariantId": 142943,
                    "merchantProductVariantReferenceKey": "index_ad",
                    "merchantReservationKey": None,
                    "name": "Comfort Select",
                    "orderItemId": 66254693892160,
                    "packagingGroupId": None,
                    "price": 100,
                    "priceWithoutTax": 79,
                    "productVariantId": 142943,
                    "quantity": 1,
                    "shippingWarehouseReferenceKey": "FRAME",
                    "tax": 21,
                    "taxAmount": 21,
                    "vendorReferenceKey": None,
                    "vendorSize": None,
                    "warehouseReferenceKey": "FRAME",
                },
                {
                    "attributes": [
                        {
                            "isLocked": False,
                            "name": "rxTintingType",
                            "type": "simple",
                            "value": "col",
                        },
                        {
                            "isLocked": False,
                            "name": "rxTintingCoating",
                            "type": "simple",
                            "value": "rshc",
                        },
                        {
                            "isLocked": False,
                            "name": "rxTintingColor",
                            "type": "simple",
                            "value": "g1",
                        },
                        {
                            "isLocked": False,
                            "name": "rxTintingHexColorCode",
                            "type": "simple",
                            "value": "#143723",
                        },
                        {
                            "isLocked": False,
                            "name": "rxTintingColorDescription",
                            "type": "localizedString",
                            "value": {
                                "cs_CZ": "šedozelená",
                                "de_CH": "Grau-Grün",
                                "de_DE": "Grau-Grün",
                                "fr_CH": "Gris-vert",
                                "it_CH": "Grigio-verde",
                                "pl_PL": "szaro-zielony",
                            },
                        },
                        {
                            "isLocked": False,
                            "name": "rxTintingAbsorption",
                            "type": "simple",
                            "value": "85",
                        },
                        {
                            "isLocked": False,
                            "name": "isSellableForFree",
                            "type": "simple",
                            "value": "True",
                        },
                        {
                            "isLocked": False,
                            "name": "rxVariantSorting",
                            "type": "simple",
                            "value": "56",
                        },
                        {
                            "isLocked": False,
                            "name": "rxAdditionalInfo",
                            "type": "localizedString",
                            "value": {
                                "de_DE": "Color, Grau-Grün 85%, Rückentspiegelt, "
                                "hard coated, clean coated"
                            },
                        },
                    ],
                    "currencyCode": "EUR",
                    "customData": {
                        "aybaOttoReservationDetails": [],
                        "hideSubItem": True,
                        "shopId": 10005,
                    },
                    "id": 17007,
                    "itemGroup": {
                        "id": "28486286",
                        "isMainItem": False,
                        "isRequired": True,
                    },
                    "localizedName": "Barva čoček do slunečních brýlí",
                    "merchantKey": "default",
                    "merchantProductVariantId": 142999,
                    "merchantProductVariantReferenceKey": "ad_tinting_col-g185-rshc",
                    "merchantReservationKey": None,
                    "name": "Sonnen­brillen­tönung",
                    "orderItemId": 66254693892161,
                    "packagingGroupId": None,
                    "price": 200,
                    "priceWithoutTax": 158,
                    "productVariantId": 142999,
                    "quantity": 1,
                    "shippingWarehouseReferenceKey": "FRAME",
                    "tax": 21,
                    "taxAmount": 42,
                    "vendorReferenceKey": None,
                    "vendorSize": None,
                    "warehouseReferenceKey": "FRAME",
                },
                {
                    "attributes": [
                        {
                            "isLocked": False,
                            "name": "rxVariantSorting",
                            "type": "simple",
                            "value": "83",
                        },
                        {
                            "isLocked": False,
                            "name": "isSellableForFree",
                            "type": "simple",
                            "value": "True",
                        },
                        {
                            "isLocked": False,
                            "name": "rxAdditionalInfo",
                            "type": "localizedString",
                            "value": {"de_DE": ""},
                        },
                    ],
                    "currencyCode": "EUR",
                    "customData": {
                        "aybaOttoReservationDetails": [],
                        "hideSubItem": True,
                        "shopId": 10005,
                    },
                    "id": 17008,
                    "itemGroup": {
                        "id": "28486286",
                        "isMainItem": False,
                        "isRequired": True,
                    },
                    "localizedName": "Přizpůsobení brýlí v pobočce Fielmann",
                    "merchantKey": "default",
                    "merchantProductVariantId": 143033,
                    "merchantProductVariantReferenceKey": "service_fitting",
                    "merchantReservationKey": None,
                    "name": "Anpassung in einer Fielmann-Niederlassung",
                    "orderItemId": 66254693892162,
                    "packagingGroupId": None,
                    "price": 200,
                    "priceWithoutTax": 158,
                    "productVariantId": 143033,
                    "quantity": 1,
                    "shippingWarehouseReferenceKey": "FRAME",
                    "tax": 21,
                    "taxAmount": 42,
                    "vendorReferenceKey": None,
                    "vendorSize": None,
                    "warehouseReferenceKey": "FRAME",
                },
            ],
            "tax": 20,
            "taxAmount": 2000,
            "vendorReferenceKey": None,
            "vendorSize": None,
            "warehouseReferenceKey": "FRAME",
        },
    ],
    "languageCode": "cs_DE",
    "orderId": 66254693892148,
    "orderReferenceKey": "fade-10005-66254693892148",
    "paymentMethod": "paypal_instant",
    "shopId": 10005,
    "shopKey": "fa",
    "vendorReferenceKey": None,
}
